project: 
  type: book
  output-dir: _book

execute:
  freeze: auto
  
book:
  title: "Chrissy's Book"
  author: "Chrissy Roberts"
  date: last-modified 
  description: "This is a template for a book I may write" 
 
  sidebar:
    logo: "images/mugshot.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://orcid.org/0000-0003-1064-5980
        text: "ORCID"
      - icon: github
        href: https://github.com/chrissyhroberts
        text: "Github"
      - icon: twitter
        href: https://twitter.com/chrissyhroberts
        text: "Twitter"         

    style: "docked"
    search: true
  page-footer:
    left: |
      Test text  
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://chrissyhroberts.github.io/hub/
  repo-url: https://github.com/chrissyhroberts/hub
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - chapters/Chapter_1.qmd
 #   - 02-lab-culture-philosophy.qmd
 #   - 03-code-of-conduct.qmd
 #   - 04-onboarding.qmd
 #   - 05-expectations.qmd
 #   - 06-offboarding.qmd
 #   - 07-funding.qmd
 #   - 08-communication.qmd
 #   - 09-academics.qmd
 #   - 10-courses.qmd
 #   - 11-computing.qmd
 #   - 12-umassd-resources.qmd
#    - 13-smast-resources.qmd
#    - 14-other-faylab-resources.qmd  


# not sure what the following line does; those files are present
bibliography: [references.bib]